name: Release

on:
  push:
    branches:
      - 'dev'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v2
        with:
            node-version: 16.18
      - name: release
        
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: release ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates : true


        