name: Release

on:
  push:
    branches:
      - 'dev'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: issue
          release_name: release ${{ github.ref_name }}


        