name: Release

on:
  push:
    branches:
      - 'dev'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: release
        uses: actions/create-release@v1
        with:
          tag_name: name
          release_name: Release