name: Release

on:
  push:
    branches:
      - 'dev'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: release
        id: release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: name
          release_name: Release
          draft: false
          prerelease: false
        